import fs from 'fs';
import path from 'path';
import nacl from 'tweetnacl';

// Reuses the EXACT same module the mobile app ships with and the existing CLI
// already uses — single source of truth for the license format/algorithm.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const licenseCore = require('../../../lib/license/licenseCore') as {
  LIMIT_TOKENS: Record<string, string>;
  TOKEN_TO_LIMIT: Record<string, number>;
  base64ToBytes: (b64: string) => Uint8Array;
  asciiToBytes: (str: string) => Uint8Array;
  buildMessage: (deviceId: string, limitToken: string) => string;
  formatLicenseCode: (deviceId: string, limitToken: string, signature: Uint8Array) => string;
};

const KEYS_PATH = path.join(__dirname, '../../../scripts/license-admin/keys/private-key.json');

let cachedSecretKey: Uint8Array | null = null;

function loadSecretKey(): Uint8Array {
  if (cachedSecretKey) return cachedSecretKey;

  // Production (Railway): the key is never on disk — it's a deploy-time secret.
  const envKey = process.env.LICENSE_PRIVATE_KEY_BASE64;
  if (envKey) {
    cachedSecretKey = licenseCore.base64ToBytes(envKey);
    return cachedSecretKey;
  }

  // Local dev fallback: the gitignored key file generated by generate-keypair.js.
  if (!fs.existsSync(KEYS_PATH)) {
    throw new Error(
      `No private key found. Set LICENSE_PRIVATE_KEY_BASE64 in the environment, or run ` +
        `"node scripts/license-admin/generate-keypair.js" from the ManagerX root for local dev (expected at ${KEYS_PATH}).`
    );
  }
  const { secretKeyBase64 } = JSON.parse(fs.readFileSync(KEYS_PATH, 'utf8'));
  cachedSecretKey = licenseCore.base64ToBytes(secretKeyBase64);
  return cachedSecretKey;
}

export const LIMIT_TOKENS = licenseCore.LIMIT_TOKENS;
export const PLAN_NAMES = Object.keys(licenseCore.LIMIT_TOKENS);

export function isValidPlan(plan: string): boolean {
  return Object.prototype.hasOwnProperty.call(licenseCore.LIMIT_TOKENS, plan);
}

export function isValidDeviceId(deviceId: string): boolean {
  return /^MX-DV-[A-Z0-9]{4}-[A-Z0-9]{4}$/i.test(deviceId);
}

export function signLicense(deviceId: string, plan: string): string {
  const limitToken = licenseCore.LIMIT_TOKENS[plan];
  if (!limitToken) throw new Error(`Unknown plan "${plan}"`);

  const deviceIdNormalized = deviceId.toUpperCase();
  const secretKey = loadSecretKey();
  const message = licenseCore.buildMessage(deviceIdNormalized, limitToken);
  const signature = nacl.sign.detached(licenseCore.asciiToBytes(message), secretKey);
  return licenseCore.formatLicenseCode(deviceIdNormalized, limitToken, signature);
}
